### ISSUE TITLE
QC steps for target data

### ISSUE THREAD

**Issue by erskck1** [kauwelab/PolyRiskScore#415]
Hi, 

Should I perform the QC steps mentioned [here](https://choishingwan.github.io/PRS-Tutorial/target/) to my target data or does PRSKB do this for me too? 

Thanks,
Ersoy

**Comment by miller34** [comment]
Hi Ersoy,
Thank you for your interest in PRSKB. If you are using your own GWAS summary statistics, then you will need to perform QC. If you are choosing the summary statistics from one of the studies included in PRSKB, then the QC steps have already been done. We still recommend that you include a reasonable sample size (recommended 100+) unless you choose to use the UK biobank/1000 Genomes minor allele frequencies, but the other steps (liftover of reference genome, cleaning up ambiguous SNPs, etc.) have already been done and are ready for you to use.

**Comment by erskck1** [comment]
Hi Miller, 
Thank you very much. It is clear enough to me now. 
Best
