### ISSUE TITLE
Comparison to PRSIce-2

### ISSUE THREAD

**Issue by erskck1** [kauwelab/PolyRiskScore#426]
Hi, 

My question is about the (Comparison with PRSIce-2) section in the publication. In this section, you compared the distribution of both PRS results of PRSIce-2 and PRSKB. The question is, why didn't you report the correlation between the two results? It is clear that they have a identical distrubition but I would also like to know how was the correlation. Is there any way to know which parameters and SNPs you have entered into PRSIce-2?

Thanks and best regards,
Ersoy

**Comment by MattCloward** [comment]
Thank you for your questions and I apologize that this information was not more readily available!
I am looking for this information and will hopefully find it for you in the next few days.

**Comment by MattCloward** [comment]
I apologize for my extreme delay in answering your questions.

I have attached the log file of the PRSice2 analysis, which contains the settings used. I have replaced all paths with example paths instead. Specifically though, here is the command I ran:

`Rscript "${PRSICE_DIR}/PRSice.R" --dir . --prsice "${PRSICE_DIR}/PRSice_linux" --base \"${assocFilePath}\" --target "${TARGET_DATA_SET}" --thread 4 --stat OR --binary-target T --no-regress --keep-ambig --out \"${OUT_DIR}/${targetDataName}_${assocFileName}\"`

As for your other question, we chose to report a Welch’s two-sample t-test which accomplishes the same result as a correlation. However, here is the result of a Pearson correlation: 
Correlation = 0.9994441
p-value =<2.2e-16

[PRSice2-GCST002245.log](https://github.com/kauwelab/PolyRiskScore/files/11141160/PRSice2-GCST002245.log)

**Comment by erskck1** [comment]
Hi Matthew, 
Thank you very much for this issue too! It is clear to me now, we can close the issue.
Best, Ersoy
