### ISSUE TITLE
ERROR DURING CALCULATION... Quitting - While using PolyRiskScore/static/sample.vcf

### ISSUE THREAD

**Issue by alisondiazc** [kauwelab/PolyRiskScore#430]
Greetings to the creators of PRSKB tool. I am trying to perform a test with the provided VCF file at PolyRiskScore/static/sample.vcf, and I encountered the error "ERROR DURING CALCULATION... Quitting," which seems to be caused by errors during the execution of the script parse_associations.py. Could you guide me on what could be causing this error? Alternatively, could you provide a sample file that allows me to observe the correct functioning of the tool, so that I can then adapt my input VCF?

The command I am using is "./runPrsCLI.sh -f /root/PRSKB/sample.1.vcf -o /root/PRSKB/sample.1.PRS.json -c 0.05 -r hg38 -p AMR." The version I am using is "1.9.0."

**Comment by mpage21** [comment]
Hi @alisondiazc,

You say that the errors seem to come from the `parse_associations.py` script. Were there additional error messages that led to you to that conclusion? If you could add them here, that would be very helpful.

**Comment by mpage21** [comment]
@alisondiazc  just checking back to see if you could post the error messages.  Otherwise, in August we will close this issue.
