### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by ngslabex** [kauwelab/PolyRiskScore#432]
Is it possible to run offline mode?
Thanks.

**Comment by mfasold** [comment]
Maybe I did just run in the same issue. 

Do you actually have internet available? PRSKB checks for an existing internet connection in [this line](https://github.com/kauwelab/PolyRiskScore/blob/b41e3538ab3886f0ad173ee9ad8141241560c46a/static/downloadables/connect_to_server.py#L897). However, that line does not work as intended. I have internet, and the check fails. The tool will continue to run if you comment the line out.

**Comment by miller34** [comment]
Yes. You can run the PRSKB in offline mode using the -s option. -s 1 requires internet to pull the database locally, which -s 2 does not require an internet connection. https://polyriskscore.readthedocs.io/en/latest/#step-number-s
